export const LoadingState = [
  'Initializing Client',
  'Initializing HTML',
  'Initializing CSS',
  'Commencing JavaScript',
  // 'Activating Styles',
  // 'Activating Scripts',
  // 'Loading Animations',
  // 'Vitals: Complete',
  // 'Loading Geographic Data',
  // 'Performance: Green',
  // 'Accessibility: Error',
  // 'Equipment Authentication: Complete',
  // 'Equipment Status: Green',
  // 'Initializing API Connection',
  'Initializing Server',
  'All Systems Green',
  'Systems Preparations Complete',
]
